### ISSUE TITLE
When in "play mode": The errors logged and given should be improved when data does not exist

### ISSUE THREAD

**Issue by nostra** [amedia/regurgitator#12]
To illustrate: Start regurgitator, put it in "play" mode, try to read a page by proxy. This will give some ugly messages. Improve if possible.

The proxy itself should probably give a 502 Bad Gateway to the client.

**Comment by lazee** [comment]
The problem then is do differ between that 502 and other 502's that are actually stored by the proxy. Given that we want Regurgitator to be able to store such responses as well.

**Comment by nostra** [comment]
Thinking about it, I do not think it makes any difference. Let's say you record a 502, which indicates you have a gateway problem. During "play", you will get a 502. The error message as such will be different, but that should not be of any consequence.
