### ISSUE TITLE
DiskStorage uses default encoding when reading/writing Strings from/to files, causing issues with non-ascii characters

### ISSUE THREAD

**Issue by fredriv** [amedia/regurgitator#14]
DiskStorage should always read and write files using the same encoding.

DiskStorage currently reads and writes responses and metadata using apache commons FileUtils and IOUtils. However, it does not specify the character encoding to use for Strings, and thus ends up using the default encoding on the current platform. This causes problems when mock responses are written and read on different systems (has caused test failures in Jenkins).

**Comment by lazee** [comment]
I will fix

**Comment by fredriv** [comment]
I have a fix locally but don't have permission to push to the repository.

**Comment by lazee** [comment]
Yes, you do ;)

**Comment by nostra** [comment]
@fredriv , @lazee : No need with repository permissions. Just fork and make a pull request.

**Comment by fredriv** [comment]
Ah, I didn't realize the repo is public.

Mvh,
-- 
Fredrik Vraalsen
Iterate AS

E-mail: vraalsen@iterate.no
Mobile: 98 46 22 55
